### ISSUE TITLE
feature req update negpip for flux

### ISSUE THREAD

**Issue by za-wa-n-go** [pamparamm/ComfyUI-ppm#10]
https://x.com/hakomikanx/status/1844710918598635663?t=HqT0aY3yJ581zHpljGhKqA&s=19

**Comment by za-wa-n-go** [comment]
I am testing the current NegPip with SDXL, but it doesn't seem to be working.

**Comment by pamparamm** [comment]
SDXL with NegPip should work correctly, can you send me your workflow? Also, NegPip can be incompatible with some other custom nodes (such as [smZNodes](https://github.com/shiimizu/ComfyUI_smZNodes))

As for FLUX, I can try implementing that.

**Comment by pamparamm** [comment]
Also you shouldn't use commas after emphasis weight: use (realistic,:-1.5) instead of (realistic:-1.5,)

**Comment by pamparamm** [comment]
Can you check if this workflow works correctly for you? Save the image and drag-and-drop it into ComfyUI
![workflow_negpip](https://github.com/user-attachments/assets/c241a400-2957-4b63-bc5e-b845b4934432)

**Comment by za-wa-n-go** [comment]
Thank you. I looked into it, and it seems to be working. It appears that the effect was weaker than I had imagined.

**Comment by pamparamm** [comment]
FLUX support done in 2a77314

**Comment by whitepapercg** [comment]
> FLUX support done in [2a77314](https://github.com/pamparamm/ComfyUI-ppm/commit/2a77314d8efc89df21f24d308ebcf551d24182ef)

I repeat your workflow 1 in 1 except for using t5xxl_fp8 instead of fp16 and don't get any effect
