### ISSUE TITLE
When using CLIPNegPip with Flux, NegPip has no effect if T5 is fp8.

### ISSUE THREAD

**Issue by umiyuki** [pamparamm/ComfyUI-ppm#12]
As the title says, when using t5xxl_fp8_e4m3fn.safetensors, NegPip has no effect. it worked fine when T5 is fp16 or GGUF.

![image](https://github.com/user-attachments/assets/d91772f2-9485-4e1a-9330-adb93be31641)
![image](https://github.com/user-attachments/assets/e52370ef-9777-4bf6-bfb7-e2dc77beb708)

**Comment by pamparamm** [comment]
Should be fixed after 1d8299c, but I'm not entirely sure

**Comment by umiyuki** [comment]
Thanks for the fix. fp16, fp8 and GGUF all worked fine.
