### ISSUE TITLE
All schedulers (ays+, GITS, etc...) are no longer available in all samplers

### ISSUE THREAD

**Issue by Djanghost** [pamparamm/ComfyUI-ppm#8]
Probably due to updates.

**Comment by pamparamm** [comment]
I can't reproduce this problem. Seems like nothing breaking was done inside `comfy.samplers` module.
Have you checked if everything works for you on a latest ComfyUI commit without other custom nodes aside `ComfyUI-ppm`?

**Comment by Djanghost** [comment]
Thanks for your anwser, well I just deleted the node and reinstalled it as mentioned on your page and it works. I apologize for the inconvenience, my bad !
